### PR TITLE
correcting regex for kebab-case

### PR DESCRIPTION
**Pull request by msalar-din**
`i18n-test.ts` is a perfectly valid kebab-case filename. But the regex in the plugin was rejecting it.

This also makes me realise, the other regexes are also missing a `0-9` in the first token.

Thanks allot for the plugin.

### CODE REVIEW

**Review by DukeLuo — CHANGES_REQUESTED** [review]
Thank you for the pull request, but I have found some issues with the change. Please update this PR.

- I agree `i18n-test.ts` is a valid kebab-case filename, but this change will also match some other filename like `18n-test.ts`, whick it's a invalid kebab-case

- `+([a-z0-9])*(-+([a-z0-9]))` is a glob expression, please modify the commit message

**Comment by msalar-din** [comment]
@DukeLuo changes pushed, please review.

**Comment by msalar-din** [comment]
> `+` means content need to be matched at lease 1 time, so `+([a-z])+([a-z0-9])*(-+([a-z0-9]))` cant match the valid kebab-case style filename `a-b.ts`. The `+([a-z])*([a-z0-9])*(-+([a-z0-9]))` is better.

Correct! Thanks for catching that, fixed!

**Comment by DukeLuo** [comment]
This PR is merged. It will release in next version. Thanks!

**Comment by DukeLuo** [comment]
The PR has been released in version 1.2.3. Thanks!

**Pull request merged**
